### ISSUE TITLE
Create a login and signup page

### ISSUE THREAD

**Issue by JhonatanDP** [JhonatanDP/just-tech-news#7]
* As a user, I can visit a login page to create a new account or log into an existing account.

  * As a user, I want to stay logged in even if I refresh the page or close the browser tab.

  * As a user, I can click a "logout" button for the app to forget me.

**Comment by cisnejo** [comment]
I'd like to give this a shot if you want to assign it to me. Do you have any specific auth paradigms you want to follow?

**Comment by cisnejo** [comment]
I see this is now closed. Is there anything more that needs to be done?

**Comment by JhonatanDP** [comment]
No really, but thank you
